platform:ios, '6.0'
pod 'SVProgressHUD'
pod 'MDRadialProgress'
pod 'ViewDeck', '>=2.3.1'
pod 'Reachability', '>=3.1.1'
pod 'EDStarRating', '>=1.1'
pod 'TPKeyboardAvoiding', '>=1.2.3'
pod 'PayPal-iOS-SDK', '>=2.0.1'
pod 'SZTextView'
pod 'UIImage-Categories'
pod 'AFNetworking', '>=2.1.0'
pod 'PHFComposeBarView', '=1.1.1'
pod 'Mixpanel'